---
- name: Execute Jenkins Pipeline for MiniProject
  hosts: localhost
  tasks:
    - name : Docker Image Build
      shell: |
        docker build -t calculator:latest .
      become: yes
    
    - name : Docker Push Image
      shell: |
        docker push jaraxxx/calculator:latest
      become: yes



