---
- name: Execute Jenkins Pipeline for MiniProject
  hosts: localhost
  tasks:
    - name: Jenkins Configuration
      jenkins_script:
        url: http://localhost:8080  # URL of your Jenkins server
        user: root
        password: root
        script: >
          import jenkins.model.*
          def job = Jenkins.instance.getItemByFullName('Ansible')
          def build = job.scheduleBuild2(0)
    - name: Clear Workspace
      shell: |
        rm -rf SPE
      become: yes

    - name: Git Checkout
      shell: |
        git clone "https://github.com/Jaraxxxx/SPE.git"
      become: yes

    - name: Build CMake
      shell: |
        cd SPE/MiniProject
        rm -rf build
        cmake -B build -G "Unix Makefiles"
        cmake --build build
      become: yes

    - name: Executing Test
      shell: |
        cd SPE/MiniProject/build
        ./Calculator_test
      become: yes

- name: Create and run Jenkins pipeline
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install Jenkins CLI
      get_url:
        url: http://localhost:8080/jnlpJars/jenkins-cli.jar
        dest: /tmp/jenkins-cli.jar
    
  - name: Run Jenkins Pipeline
    copy:
      content: |
        pipeline {
            agent any
            stages {
                stage('Interactive Stage') {
                    steps {
                        script {
                            // Here you can run your interactive script
                            sh 'echo "Hello Jenkins!"'
                            sh 'echo "Press any key to continue..."'
                            sh 'read'
                            sh 'echo "Continuing..."'
                        }
                    }
                }
            }
        }
      dest: /tmp/Jenkinsfile
    command: java -jar /tmp/jenkins-cli.jar -s http://localhost:8080/ -auth root:root build 'InteractivePipeline' -f -p INTERACTIVE=true
    args:
      chdir: /tmp