---
- name: Execute Jenkins Pipeline for MiniProject
  hosts: localhost
  tasks:
    - name: Clear Workspace
      shell: |
        rm -rf SPE
      become: yes

    - name: Git Checkout
      shell: |
        git clone "https://github.com/Jaraxxxx/SPE.git"
      become: yes

    - name: Build CMake
      shell: |
        cd SPE/MiniProject
        rm -rf build
        cmake -B build -G "Unix Makefiles"
        cmake --build build
      become: yes
    
    - name: Run Tests
      shell: |
        cd SPE/MiniProject/build
        ./Calcultor_test
      become: yes
    
    - name : Docker Image Build
      shell: |
        docker build -t calculator:latest .
      become: yes
    
    - name : Docker Push Image
      shell: |
        docker push jaraxxx/calculator:latest
      become: yes



