- name: docker build and push
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/
        username: jaraxxx
        password: 8850752290 
    
    - name: Build Docker Image
      command: docker build -t calculator .

    - name: tag image
      command: docker tag calculator jaraxxx/calculator:latest

    - name: Push image
      command: docker push jaraxxx/calculator:latest