- name: docker build and push
  hosts: localhost

  tasks:
    - name: Delete build directory
      command: rm -rf build

    - name: Create build directory
      command: mkdir build

    - name: Build Docker Image
      command: docker build -t calculator .

    - name: tag image
      command: docker tag calculator jaraxxx/calculator:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/
        username: jaraxxx
        password: 8850752290 

    - name: Push image
      command: docker push jaraxxx/calculator:latest