- name: kubernetes deployment
  hosts: localhost

  tasks:
    - name: delete previous deployment
      command: kubectl delete deployment calculator
    - name: delete previous service
      command: kubectl delete service calculator
    - name: deploy calculator on kubernetes
      command: kubectl apply -f calculator-deployment.yaml
    - name: create service
      command: kubectl apply -f calculator-service.yaml