- name: kubernetes deployment
  hosts: localhost

  tasks:
    - name: delete previous deployment
      command: kubectl delete deployment calculator-deployment

    - name: delete previous service
      command: kubectl delete service calculator-service

    - name: deploy calculator on kubernetes
      command: kubectl apply -f calculator-app-deployment.yml

    - name: create service
      command: kubectl apply -f calculator-app-service.yml